"""Builds the in-app bear stage images (run: python3 assets/source/make_bears.py).

Reads the ten originals in assets/source/bears/ (baby_oski.png ... max_oski.png), writes
assets/bears/stage-01.jpg ... stage-10.jpg (1024px wide, so the app stays small), and
src/config/bearImages.ts with each picture's sky colour (used to fill the strip that shows
above the bear while the press animation squashes it).
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
NAMES = ['baby', 'small', 'young', 'growing', 'strong', 'big', 'huge', 'massive', 'legendary', 'max']
WIDTH = 1024

skies = []
total = 0
for i, name in enumerate(NAMES, start=1):
    im = Image.open(os.path.join(HERE, 'bears', f'{name}_oski.png')).convert('RGB')
    height = round(im.height * WIDTH / im.width)
    im = im.resize((WIDTH, height), Image.LANCZOS)
    out = os.path.join(ROOT, 'assets', 'bears', f'stage-{i:02d}.jpg')
    im.save(out, quality=88, optimize=True, progressive=True)
    total += os.path.getsize(out)
    # average of the top few rows = the sky just above the picture's edge
    strip = im.crop((0, 0, WIDTH, 6)).resize((1, 1), Image.BOX).getpixel((0, 0))
    skies.append('#%02x%02x%02x' % strip)
    print(name, im.size, os.path.getsize(out) // 1024, 'KB', skies[-1])

lines = ['// Generated by assets/source/make_bears.py. Do not edit by hand.', '',
         '/** The 4:3 picture for each bear stage (1-10), and the sky colour along its top edge. */',
         'export const BEAR_ASPECT = %d / %d;' % (WIDTH, height), '',
         'export const BEAR_IMAGES: Record<number, { source: number; sky: string }> = {']
for i, sky in enumerate(skies, start=1):
    lines.append("  %d: { source: require('../../assets/bears/stage-%02d.jpg'), sky: '%s' }," % (i, i, sky))
lines += ['};', '']
open(os.path.join(ROOT, 'src', 'config', 'bearImages.ts'), 'w').write('\n'.join(lines))
print('total', total // 1024, 'KB')
