"""Builds the in-app bear stage images (run: python3 assets/source/make_bears.py).

Reads the originals in assets/source/bears/: <name>_oski.png (lockout, one per stage) and,
where all four exist, the press frames <name>_oski_mid / _eyes / _nose / _bottom.png.
Writes assets/bears/stage-NN.jpg and stage-NN-<frame>.jpg (1024px wide, so the app stays
small) and src/config/bearImages.ts: each stage's picture, its sky colour (fills the strip
above the bear in the squash fallback), and, when it has the press frames, the five frames
in order (lockout, mid, eyes, nose, bottom) with the barbell's height in each (used to time
the animation to the bar's real travel).
"""
import os
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
FRAME_TAGS = ['mid', 'eyes', 'nose', 'bottom']
NAMES = ['baby', 'small', 'young', 'growing', 'strong', 'big', 'huge', 'massive', 'legendary', 'max']
WIDTH = 1024

def bar_height(path):
    """Row (in the original picture) where the white barbell bar is: the row with the most white."""
    a = np.array(Image.open(path).convert('RGB')).astype(int)
    white = (a[..., 0] > 225) & (a[..., 1] > 225) & (a[..., 2] > 225)
    white[:, :400] = False
    white[:, 1100:] = False
    white[850:, :] = False
    return int(np.argmax(white.sum(axis=1)))


def shrink(src, out):
    im = Image.open(src).convert('RGB')
    height = round(im.height * WIDTH / im.width)
    im = im.resize((WIDTH, height), Image.LANCZOS)
    im.save(out, quality=88, optimize=True, progressive=True)
    return im, os.path.getsize(out)


entries = []
total = 0
for i, name in enumerate(NAMES, start=1):
    top = os.path.join(HERE, 'bears', f'{name}_oski.png')
    im, size = shrink(top, os.path.join(ROOT, 'assets', 'bears', f'stage-{i:02d}.jpg'))
    total += size
    height = im.height
    # average of the top few rows = the sky just above the picture's edge
    sky = '#%02x%02x%02x' % im.crop((0, 0, WIDTH, 6)).resize((1, 1), Image.BOX).getpixel((0, 0))
    paths = [os.path.join(HERE, 'bears', f'{name}_oski_{tag}.png') for tag in FRAME_TAGS]
    frames = all(os.path.exists(p) for p in paths)
    bars = None
    order = list(FRAME_TAGS)
    if frames:
        measured = {tag: bar_height(p) for tag, p in zip(FRAME_TAGS, paths)}
        # order the press frames by how low the bar is, so a mislabelled file can't scramble the rep
        order = sorted(FRAME_TAGS, key=lambda tag: measured[tag])
        bars = [bar_height(top)] + [measured[tag] for tag in order]
        if order != list(FRAME_TAGS):
            print('  note: frames reordered by bar height:', order)
        for tag, src in zip(FRAME_TAGS, paths):
            _, size = shrink(src, os.path.join(ROOT, 'assets', 'bears', f'stage-{i:02d}-{tag}.jpg'))
            total += size
    entries.append((i, sky, bars, order))
    print(name, im.size, sky, f'press frames, bar y {bars}' if bars else '-')

lines = ['// Generated by assets/source/make_bears.py. Do not edit by hand.', '',
         '/**',
         ' * The 4:3 picture for each bear stage (1-10) and the sky colour along its top edge.',
         ' * `frames` (when present) are the shoulder-press poses, lockout first and bottom last.',
         ' */',
         'export const BEAR_ASPECT = %d / %d;' % (WIDTH, height), '',
         'export interface BearArt {', '  source: number;', '  sky: string;', '  /** lockout first, bottom last */', '  frames?: number[];', '  /** where the barbell is in each frame (pixels in the original), to time the animation */', '  bar?: number[];', '}', '',
         'export const BEAR_IMAGES: Record<number, BearArt> = {']
for i, sky, bars, order in entries:
    base = "require('../../assets/bears/stage-%02d.jpg')" % i
    if bars:
        lines.append('  %d: {' % i)
        lines.append('    source: %s,' % base)
        lines.append("    sky: '%s'," % sky)
        lines.append('    frames: [')
        lines.append('      %s,' % base)
        for tag in order:
            lines.append("      require('../../assets/bears/stage-%02d-%s.jpg')," % (i, tag))
        lines.append('    ],')
        lines.append('    bar: [%s],' % ', '.join(str(b) for b in bars))
        lines.append('  },')
    else:
        lines.append("  %d: { source: %s, sky: '%s' }," % (i, base, sky))
lines += ['};', '']
open(os.path.join(ROOT, 'src', 'config', 'bearImages.ts'), 'w').write('\n'.join(lines))
print('total', total // 1024, 'KB')
