"""Builds the in-app bear stage images (run: python3 assets/source/make_bears.py).

Reads the originals in assets/source/bears/: <name>_oski.png (lockout, one per stage) and,
where they exist, <name>_oski_mid.png and <name>_oski_bottom.png (the press frames).
Writes assets/bears/stage-NN.jpg, stage-NN-mid.jpg, stage-NN-bottom.jpg (1024px wide, so the
app stays small) and src/config/bearImages.ts: each stage's picture, its sky colour (fills the
strip above the bear in the squash fallback), and its press frames when it has both.
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
NAMES = ['baby', 'small', 'young', 'growing', 'strong', 'big', 'huge', 'massive', 'legendary', 'max']
WIDTH = 1024

def shrink(src, out):
    im = Image.open(src).convert('RGB')
    height = round(im.height * WIDTH / im.width)
    im = im.resize((WIDTH, height), Image.LANCZOS)
    im.save(out, quality=88, optimize=True, progressive=True)
    return im, os.path.getsize(out)


entries = []
total = 0
for i, name in enumerate(NAMES, start=1):
    top = os.path.join(HERE, 'bears', f'{name}_oski.png')
    im, size = shrink(top, os.path.join(ROOT, 'assets', 'bears', f'stage-{i:02d}.jpg'))
    total += size
    height = im.height
    # average of the top few rows = the sky just above the picture's edge
    sky = '#%02x%02x%02x' % im.crop((0, 0, WIDTH, 6)).resize((1, 1), Image.BOX).getpixel((0, 0))
    mid = os.path.join(HERE, 'bears', f'{name}_oski_mid.png')
    bottom = os.path.join(HERE, 'bears', f'{name}_oski_bottom.png')
    frames = os.path.exists(mid) and os.path.exists(bottom)
    if frames:
        for tag, src in (('mid', mid), ('bottom', bottom)):
            _, size = shrink(src, os.path.join(ROOT, 'assets', 'bears', f'stage-{i:02d}-{tag}.jpg'))
            total += size
    entries.append((i, sky, frames))
    print(name, im.size, sky, 'press frames' if frames else '-')

lines = ['// Generated by assets/source/make_bears.py. Do not edit by hand.', '',
         '/**',
         ' * The 4:3 picture for each bear stage (1-10) and the sky colour along its top edge.',
         ' * `frames` (when present) are the shoulder-press poses: [lockout, middle, bottom].',
         ' */',
         'export const BEAR_ASPECT = %d / %d;' % (WIDTH, height), '',
         'export interface BearArt {', '  source: number;', '  sky: string;', '  frames?: [number, number, number];', '}', '',
         'export const BEAR_IMAGES: Record<number, BearArt> = {']
for i, sky, frames in entries:
    base = "require('../../assets/bears/stage-%02d.jpg')" % i
    if frames:
        lines.append('  %d: {' % i)
        lines.append('    source: %s,' % base)
        lines.append("    sky: '%s'," % sky)
        lines.append('    frames: [')
        lines.append('      %s,' % base)
        lines.append("      require('../../assets/bears/stage-%02d-mid.jpg')," % i)
        lines.append("      require('../../assets/bears/stage-%02d-bottom.jpg')," % i)
        lines.append('    ],')
        lines.append('  },')
    else:
        lines.append("  %d: { source: %s, sky: '%s' }," % (i, base, sky))
lines += ['};', '']
open(os.path.join(ROOT, 'src', 'config', 'bearImages.ts'), 'w').write('\n'.join(lines))
print('total', total // 1024, 'KB')
