// Generated by assets/source/make_bears.py. Do not edit by hand.

/**
 * The 4:3 picture for each bear stage (1-10) and the sky colour along its top edge.
 * `frames` (when present) are the shoulder-press poses: [lockout, middle, bottom].
 */
export const BEAR_ASPECT = 1024 / 768;

export interface BearArt {
  source: number;
  sky: string;
  frames?: [number, number, number];
}

export const BEAR_IMAGES: Record<number, BearArt> = {
  1: {
    source: require('../../assets/bears/stage-01.jpg'),
    sky: '#bbe5fd',
    frames: [
      require('../../assets/bears/stage-01.jpg'),
      require('../../assets/bears/stage-01-mid.jpg'),
      require('../../assets/bears/stage-01-bottom.jpg'),
    ],
  },
  2: { source: require('../../assets/bears/stage-02.jpg'), sky: '#b5e5fd' },
  3: { source: require('../../assets/bears/stage-03.jpg'), sky: '#b7e3fc' },
  4: { source: require('../../assets/bears/stage-04.jpg'), sky: '#b6e4fd' },
  5: { source: require('../../assets/bears/stage-05.jpg'), sky: '#b7e4fd' },
  6: { source: require('../../assets/bears/stage-06.jpg'), sky: '#b5e4fd' },
  7: { source: require('../../assets/bears/stage-07.jpg'), sky: '#a9d9f1' },
  8: { source: require('../../assets/bears/stage-08.jpg'), sky: '#aadcf5' },
  9: { source: require('../../assets/bears/stage-09.jpg'), sky: '#a8e1fd' },
  10: { source: require('../../assets/bears/stage-10.jpg'), sky: '#a2dffb' },
};
